name: causal_benchmark
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - causal-learn==0.1.3.6
      - networkx==3.1
      - pandas==1.5.3
      - numpy==1.23.5
      - pyyaml==6.0
      - joblib==1.3.2
      - causalnex>=0.12.0
